const Map<String, String> en = {
  //splashScreen
  'SplashscreenText': 'Discover Yourself through Personalized Astrology',
  'Welcome': 'Welcome',
  'WelcomeSubText':
    'Get daily tips, helpful insights, and a cosmic support to guide your day.',
  'PersonalizedKundli': 'Personalized Kundli',
  'PersonalizedKundliSubText':
    '  Accurate Kundli based on your date, time & place of birth',
  'MatchmakingSubText':
    'Check your compatibility with your partner using astrology.',
  'Next': 'Next',
  'Getstarted': 'Get Started',

  //Login
  'enterCode': 'Enter your verification code',
  'invalidOtp': 'Invalid OTP Number',
  'enterOtp': 'Please enter 4 digit OTP Number',
  'wrongOtp': 'Invalid OTP Number',
  'sentTo': ' Sent to',
  'didntReceive': 'Didn’t receive OTP?',
  'resend': 'Re-send',
  'verify': 'Verify',
  'privacyTitle': 'Privacy Policy',
  'tncTitle': 'Terms and Conditions',
  'tnc_Title': 'Terms & Conditions',

  //Homescreen
  'AskAstrologer': 'Ask Astrologer',
  'ViewAll': 'View All',
  'ViewDetails': 'View Details',
  'ReadMore': 'Read more',
  'ReadLess': 'Read less',
  'ReliableApp': 'Reliable App',
  'SecurePayment': 'Secure Payment',
  'TrustedAstrologer': 'Trusted Astrologer',
  'Horoscope': 'Horoscope',
  'Kundli': 'Kundli',
  'Notification': 'Notification',
  'Partner': 'Partner',
  'Panchang': 'Panchang',
  'ZodiacSign': 'Zodiac Sign',
  'LuckyNumber': 'Lucky Number',
  'LuckyColor': 'Lucky Color',
  'TodayInsights': 'Today Insights',
  'Top10blogs': 'Top 10 Blogs',
  'Weekyhoroscope': 'Weekly Horoscope',
  'VenusNaskshtra': 'Venus Naskshtra',
  'NumerologyWeekly': 'Numerology Weekly',
  'TodayMuhrat': 'Today Muhrat',
  'SunriseSunset': 'Sunrise - Sunset',
  'SunriseSunset1': 'Sunrise/Sunset',
  'MoonriseMoonset': 'Moonrise - Moonset',
  'MoonriseMoonset1': 'Moonrise/Moonset',
  'Auspicious': 'Auspicious',
  'Inauspicious': 'Inauspicious',
  'AbhijitMuhurat': 'Abhijit Muhurat',
  'Rahukaal': 'Rahu Kaal',
  'GulikaiKaal': 'Gulikai Kaal',
  'AbhijitMuhuratDescription':
    'It is an auspicious 48-minute period around midday, best for starting new and important work when no other good Muhurat is available.',
  'RahukaalDescription':
    'It is an inauspicious 1.5-hour period each day. Avoid beginning new ventures or important tasks during this time.',
  'GulikaiKaalDescription':
    'Gulikai Kaal is a daily period linked with delays and obstacles. It’s considered inauspicious for starting new work.',
  'TodayHoroscope': 'Today’s Horoscope',
  
  //ServiceScreen
  'WhatYouNeed': 'Didn’t find what you need?',
  'ConnectAstrologer': 'Connect with our astrologer.',
  'Ask': 'Ask',
  'Service': 'Service',

  //YogaScreen
  'Heading':
    'Yoga is a special combination of planets in your birth chart that influences your personality, life events, and relationships.',
  'homeTab': 'Home',
  'serviceTab': 'Service',
  'aiAstro': 'Ai Astro',
  'expertTab': 'Expert',
  'profileTab': 'Profile',

  //Profile
  'title': 'Profile',
  'name': 'What is your Name?',
  'Name': 'Name',
  'gender': 'What is your Gender?',
  'Gender': 'Gender',
  'birthTime': 'Time of Birth',
  'birthPlace': 'Place of Birth',
  'dob': 'Date of Birth',
  'logout': 'Log out',
  'logoutDesc': 'Are you sure you want to logout',
  'delete': 'Delete',
  'deleteAccountText': 'Delete Account',
  'deleteAccountDesc': 'Once deleted, this account can no longer be accessed.',
  'deleteAccountDesc1': 'Are you sure you want to delete your account?',
  'cancle': 'Cancel',
  'log_out': 'Logout',
  'deleteAccount': 'Delete Account',
  'kundliTitle': 'My Kundli',
  'FreeKundli': 'Free Kundli',
  'PremiumKundli': 'Premium Kundli',
  'Purchasedon': 'Purchased on ',
  'noKundli': 'No Kundli Found',
  'noKundilDesc': 'Unlock Kundli and see your cosmic path.',
  'getKundli': 'Get Kundli Now',
  'profileDetailsTitle': 'My Details',
  'username': 'Name',
  'userGender': 'Gender',
  'accountSetting': 'Account Settings',
  'myDetails': 'My Details',
  'SavedProfile': 'Saved Profile',
  'changeL': 'Change Language',
  'legal': 'Legal & Privacy',
  'accountAction': 'Account Actions',
  'NoDetailsFound': 'No Details Found',
  'Pleasefilldetailsforgetpersonalizedkundli':
    'Please fill details for get personalized kundli',
  'Letsgetstarted': "Let's get started",
  'SelectProfile': 'Select Profile',

  //PersonalInformationscreen
  'PersonalInformation': 'Personal Information',
  'ProfileDetails': 'My Details',
  'CompleteYourProfile': 'Complete Your Profile',
  'MatchMaking': 'Match Making',
  'KundaliAdd': 'Add Profile',
  'LetsGetStarted': "Let's get started",
  'DataRequirementText':
    'We require your data to show you all the charts and insights',
  'WhatIsYourName': 'What is your name?',
  'EnterYourName': 'Enter your name',
  'WhatIsYourGender': 'What is your gender?',
  'DateOfBirth': 'Date of birth',
  'TimeOfBirth': 'Time of birth',
  'PlaceOfBirth': 'Place of birth',
  'EnterLocation': 'Enter location',
  'SelectTime': 'Select Time',
  'SelectDate': 'Select Date',
  'Selectoftimingofbirth': 'Select timing of birth',
  'Relationship': 'Relationship (optional)',
  'Occupation': 'Occupation (optional)',
  'SelectOccupation': 'Select Occupation',
  'SaveProfile': 'Save profile',
  'Save': 'Save',
  'Proceed': 'Proceed',
  'Submit': 'Submit',
  'Location': 'Location',
  'Male': 'Male',
  'Female': 'Female',
  'ProfileDetail': 'Profile Details',

  //Validation Errors
  'NameError': 'Please enter your name',
  'GenderError': 'Please select your gender',
  'DobError': 'Please select your date of birth',
  'TobError': 'Please select your time of birth',
  'PobError': 'Please select your place of birth',
  'connectionError': 'Network error. Please check your internet connection.',

  //Panchang
  'Muhurat': 'Muhurat',
  'TithiDescription':
    'Shows the Moon’s phase and the day’s mood, whether for beginnings, celebrations, or reflection.',
  'VaarDescription':
    'Vaar is the weekday, ruled by a planet, each carrying unique energy for activities.',
  'NakshatraDescription':
    'Nakshatra is the star the Moon moves through, shaping the day’s energy and your actions.',
  'KaranaDescription':
    'Karana divides the day into parts and guides the right time for focused tasks.',
  'YogaDescription':
    'It is the Sun–Moon blend that shows if the day is balanced, strong, or challenging.',
  'Sunday': 'Sunday',
  'SundaySpecial': 'Good for leadership and new beginnings',
  'SundayLord': 'Sun',
  'Monday': 'Monday',
  'MondaySpecial': 'Good for peace, emotions, and healing',
  'MondayLord': 'Moon',
  'Tuesday': 'Tuesday',
  'TuesdaySpecial': 'Good for strength, courage, and action',
  'TuesdayLord': 'Mars',
  'Wednesday': 'Wednesday',
  'WednesdaySpecial': 'Good for communication, learning, and trade',
  'WednesdayLord': 'Mercury',
  'Thursday': 'Thursday',
  'ThursdaySpecial': 'Good for wisdom, teaching, and growth',
  'ThursdayLord': 'Jupiter',
  'Friday': 'Friday',
  'FridaySpecial': 'Good for love, beauty, and comforts',
  'FridayLord': 'Venus',
  'Saturday': 'Saturday',
  'SaturdaySpecial': 'Good for discipline, hard work, and endurance',
  'SaturdayLord': 'Saturn',
  'TITHI': 'TITHI',
  'VAAR': 'VAAR',
  'NAKSHATRA': 'NAKSHATRA',
  'KARANA': 'KARANA',
  'YOGA': 'YOGA',
  'Tithi': 'Tithi',
  'Start': 'Start',
  'End': 'End',
  'Diety': 'Diety',
  'NextTithi': 'Next Tithi',
  'Lord': 'Lord',
  'NextVaar': 'Next Vaar',
  'Nakshatra': 'Nakshatra',
  'NextNakshatra': 'Next Nakshatra',
  'Karana': 'Karana',

  //MatchMaking
  'AddPartner': 'Add Partner',
  'CheckCompatibility': 'Check Compatibility',
  'SelectPartner': 'Select Partner',
  'AddProfile': 'Add Profile',
  'EditProfile': 'Edit Profile',
  'ExcellentCompatibility': 'Excellent Compatibility',
  'CompatibilityParameters': 'Compatibility Parameters',
  'VeryPoorMatch': 'Very Poor Match',
  'VeryPoorMatchTraits': 'Major differences, frequent conflicts',
  'VeryPoorMatchDescription':
    'Major differences in values and communication. Unlikely to work without significant effort and may lead to conflicts.',
  'PoorMatch': 'Poor Match',
  'PoorMatchTraits': 'Noticeable challenges, stress',
  'PoorMatchDescription':
    'Challenges and misunderstandings are likely. Careful consideration and patience are needed to move forward.',
  'AverageMatch': 'Average Match',
  'AverageMatchTraits': 'Some common ground, need for effort',
  'AverageMatchDescription':
    'Some shared interests, but differences require compromise and effort to maintain harmony.',
  'GoodMatch': 'Good Match',
  'GoodMatchTraits': 'Balanced, manageable differences',
  'GoodMatchDescription':
    'A balanced relationship with manageable differences. Mutual support can lead to a healthy partnership.',
  'VeryGoodMatch': 'Very Good Match',
  'VeryGoodMatchTraits': 'Strong alignment, mutual support',
  'VeryGoodMatchDescription':
    'Strong compatibility in values and goals. Understanding and support help the relationship flourish.',
  'ExcellentMatch': 'Excellent Match',
  'ExcellentMatchTraits': 'Deep compatibility, long-term vision',
  'ExcellentMatchDescription':
    'High compatibility with shared vision. Trust and harmony make it ideal for long-term happiness.',
  'Varna': 'Varna',
  'VarnaMatching': 'Social and mental match, shared values',
  'Vasya': 'Vashya',
  'VasyaMatching': 'Attraction and influence',
  'Tara': 'Tara',
  'TaraMatching': 'Star match, checks couple’s health and lifespan',
  'Yoni': 'Yoni',
  'YoniMatching': 'Sexual match, balanced passion and attraction',
  'GrahaMaitri': 'Graha Maitri',
  'GrahaMaitriMatching': 'Mental friendship and compatibility',
  'Gana': 'Gana',
  'GanaMatching': 'Temperament match for a smooth relationship',
  'Bhakoot': 'Bhakoot',
  'BhakootMatching': 'Emotional bonding, prosperity, and family harmony',
  'Nadi': 'Nadi',
  'NadiMatching': 'Health, genetics, and progeny prospects',
  'NoListFound': 'No List Found',

  //Doshscreen
  'Dosh': 'Dosha',
  'DoshDescription':
    'Dosha is a planetary flaw or imbalance in a birth chart believed to bring obstacles and delays in life.',
  'MangalDosha': 'Mangal Dosha',
  'KaalsarpDosha': 'Kaalsarp Dosha',
  'PitraDosha': 'Pitra Dosha',
  'MangalDoshaDescription':
    'Mangal Dosha is when Mars in the chart causes delays or issues in marriage.',
  'KaalsarpDoshaDescription':
    'Kaalsarp Dosha occurs when all planets fall between Rahu and Ketu, bringing challenges in life.',
  'PitraDoshaDescription':
    'Pitra Dosha is when ancestral karma in the chart is believed to cause obstacles in life.',
  'Yes': 'Yes',
  'No': 'No',
  'MANGLIK': 'MANGLIK',
  'ConsultHeading': 'Consult our Astro Experts',
  'ViewMore': 'View More',

  //Dasha
  'Dasha': 'Dasha',
  'MahaDasha': 'Maha Dasha',
  'AntaraDasha': 'Antara Dasha',
  'PratyantaraDasha': 'Pratyantara Dasha',
  'MahaDashaDescription':
    'The main planetary period in Vedic astrology. It runs for several years and sets the overall theme of life events during that time.',
  'AntarDashaDescription':
    'The sub-period within a Maha Dasha, ruled by another planet. It refines and adds details to the effects of the Maha Dasha.',
  'PratyantaraDashaDescription':
    'A further subdivision within Antara Dasha. It shows more specific and shorter-term influences on daily life and events.',
  'Dasha_Mars_Abbr': 'Ma',
  'Dasha_Rahu_Abbr': 'Ra',
  'Dasha_Jupiter_Abbr': 'Ju',
  'Dasha_Saturn_Abbr': 'Sa',
  'Dasha_Mercury_Abbr': 'Me',
  'Dasha_Ketu_Abbr': 'Ke',
  'Dasha_Venus_Abbr': 'Ve',
  'Dasha_Sun_Abbr': 'Su',
  'Dasha_Moon_Abbr': 'Mo',
  'Dasha_Ascendant_Abbr': 'As',
  'Mars': 'Mars',
  'Rahu': 'Rahu',
  'Jupiter': 'Jupiter',
  'Saturn': 'Saturn',
  'Mercury': 'Mercury',
  'Ketu': 'Ketu',
  'Venus': 'Venus',
  'Sun': 'Sun',
  'Moon': 'Moon',
  'Ascendant': 'Ascendant',

  //Yoga
  'Yoga': 'Yoga',
  'YogaDescription1':
    'Yoga is a special combination of planets in your birth chart thatinfluences your personality, life events, and relationships.',

  //SadeSatiscreen
  'SadeSati': 'Sade Sati',
  'SadeSatiReport': 'Sade Sati Report',
  'SadeSatiDescription':
    'It helps users view their personalized Sade Sati period (past, current, and upcoming)',
  'Phase': 'Phase',

  //HoraMuhurat
  'HoraMuhurat': 'Hora Muhurat',
  'HoraMuhuratDescription':
    'It Allows users to view daily time-based planetary hours (Horas) and check auspicious/inauspicious timings for any date.',

  //Horoscope
  'Today': 'Today',
  'ThisWeek': 'This week',
  'Health': 'Health',
  'Love': 'Love',
  'Wealth': 'Wealth',
  'Career': 'Career',
  'Family': 'Family',
  'Friends': 'Friends',
  'Travel': 'Travel',
  'Status': 'Status',
  'Finance': 'Finance',
  'Aries': 'Aries',
  'Taurus': 'Taurus',
  'Gemini': 'Gemini',
  'Cancer': 'Cancer',
  'Leo': 'Leo',
  'Virgo': 'Virgo',
  'Libra': 'Libra',
  'Scorpio': 'Scorpio',
  'Sagittarius': 'Sagittarius',
  'Capricorn': 'Capricorn',
  'Aquarius': 'Aquarius',
  'Pisces': 'Pisces',

  //Kundliscreen
  'NowGetFree': 'Now get free',
  'Astrological': 'astrological',
  'ReportsText': 'report and make informed decisions',
  'LagnaChart': 'Lagna Chart',
  'NavamsaChart': 'Navamsa Chart',
  'ChalitChart': 'Chalit Chart',
  'Chalit': 'chalit',
  'LagnaChartDescription':
    'Lagna Chart (D1) It tells about your personality, life path, and how you face the world.',
  'Retrograde': 'Retrograde',
  'Combust': 'Combust',
  'Exalted': 'Exalted',
  'Debilitated': 'Debilitated',
  'Vargottam': 'Vargottam',
  'StillConfuse': 'Still confused reading about your Kundli?',
  'GetHelp': 'Get Help',
  'KundliHouseGuide': 'Kundli House Guide',
  'HowToRead': 'How to read Chalit chart?',
  'HowToReadNavamsa': 'How to Read Navamsa Kundali?',
  'SeeMore': 'See More',
  'SeeLess': 'See Less',
  'DownloadKundli': 'Download Kundli',
  'NavamsaChartDescription':
    'Navamsa Chart (D9) Shows your growth, values, and strengths in marriage and partnership',
  'ChalitChartDescription':
    'Chalit Chart shows how planets influence your life practically by adjusting for house positions and real experiences.',
  'AriesLaganText':
    'Your ascendant sign is Aries, which makes you a natural leader.',
  'TaurusLaganText':
    'Your ascendant sign is Taurus, which makes you reliable and steady.',
  'GeminiLaganText':
    'Your ascendant sign is Gemini, which makes you curious and adaptable.',
  'CancerLaganText':
    'Your ascendant sign is Cancer, which makes you caring and protective.',
  'LeoLaganText':
    'Your ascendant sign is Leo, which makes you confident and creative.',
  'VirgoLaganText':
    'Your ascendant sign is Virgo, which makes you practical and detail-oriented.',
  'LibraLaganText':
    'Your ascendant sign is Libra, which makes you diplomatic and charming.',
  'ScorpioLaganText':
    'Your ascendant sign is Scorpio, which makes you intense and determined.',
  'SagittariusLaganText':
    'Your ascendant sign is Sagittarius, which makes you adventurous and optimistic.',
  'CapricornLaganText':
    'Your ascendant sign is Capricorn, which makes you disciplined and responsible.',
  'AquariusLaganText':
    'Your ascendant sign is Aquarius, which makes you innovative and independent.',
  'PiscesLaganText':
    'Your ascendant sign is Pisces, which makes you compassionate and imaginative.',
  'AriesNavamText':
    'Your ascendant sign is Aries, which gives you inner courage and a pioneering spirit in relationships and personal growth.',
  'TaurusNavamText':
    'Your ascendant sign is Taurus, which makes you steady, patient, and focused on building lasting emotional security.',
  'GeminiNavamText':
    'Your ascendant sign is Gemini, which makes you mentally agile and open to learning from relationships and shared experiences.',
  'CancerNavamText':
    'Your ascendant sign is Cancer, which gives you deep emotional sensitivity and a nurturing approach to partnerships.',
  'LeoNavamText':
    'Your ascendant sign is Leo, which brings inner confidence, generosity, and a desire to express your heart fully in relationships.',
  'VirgoNavamText':
    'Your ascendant sign is Virgo, which makes you analytical, service-oriented, and concerned with improving yourself and others.',
  'LibraNavamText':
    'Your ascendant sign is Libra, which gives you a refined sense of balance, fairness, and harmony in close bonds and spiritual growth.',
  'ScorpioNavamText':
    'Your ascendant sign is Scorpio, which gives you emotional depth, resilience, and a transformative approach to intimacy and trust.',
  'SagittariusNavamText':
    'Your ascendant sign is Sagittarius, which makes you optimistic, adventurous, and spiritually driven in relationships and personal pursuits.',
  'CapricornNavamText':
    'Your ascendant sign is Capricorn, which gives you discipline, perseverance, and a responsible approach to partnership and life’s challenges.',
  'AquariusNavamText':
    'Your ascendant sign is Aquarius, which makes you idealistic, open-minded, and drawn to unconventional bonds and spiritual ideals.',
  'PiscesNavamText':
    'Your ascendant sign is Pisces, which gives you compassion, empathy, and a deep yearning for spiritual connection and unconditional love.',
  'Personality1': 'Personality',
  'Wealth1': 'Wealth',
  'Communication1': 'Communication',
  'Home1': 'Home',
  'Creativity1': 'Creativity',
  'Health1': 'Health',
  'Marriage1': 'Marriage',
  'Transformation1': 'Transformation',
  'Luck1': 'Luck',
  'Career1': 'Career',
  'Friends1': 'Friends',
  'Spirituality1': 'Spirituality',
  'House': 'House',
  'InnerSelf': 'Inner Self',
  'FamilyValues': 'Family Values',
  'MarriageEfforts': 'Marriage Efforts',
  'DomesticPeace': 'Domestic Peace',
  'LoveInMarriage': 'Love in Marriage',
  'Challenges': 'Challenges',
  'SpouseNature': 'Spouse Nature',
  'Intimacy': 'Intimacy',
  'SpiritualGrowth': 'Spiritual Growth',
  'MarriageDuty': 'Marriage Duty',
  'SpouseSupport': 'Spouse Support',
  'Isolation': 'Isolation',

  //Housescreen
  'RulingPlanet': 'Ruling Planet',
  'HouseAnalysis': 'House Analysis',
  'PlanetsOnThisHouse': 'Planets on this house',
  'Degree': 'Degree',
  'Longitude': 'Longitude',
  'Nakshatra': 'Nakshatra',
  'Pada': 'Pada',
  'Rashi': 'Rashi',
  'Lord': 'Lord',
  'Previous': 'Previous',
  
  //KundliChartRead
  'PositionOfHouses': 'Position of houses and their traits',
  'Position': 'Position',
  'Planet': 'Planet',
  'Glossary': 'Glossary',
  'HowToReadKundliChart': 'How to read Kundli Chart?',
  'Themes': 'Themes',
  'HouseTheme1': 'Personality, Health, Identity',
  'HouseTheme2': 'Wealth, Speech, Values',
  'HouseTheme3': 'Siblings, Courage, Efforts',
  'HouseTheme4': 'Home, Mother, Emotions',
  'HouseTheme5': 'Creativity, Children, Past Life',
  'HouseTheme6': 'Service, Enemies, Challenges',
  'HouseTheme7': 'Partner, Marriage, Contracts',
  'HouseTheme8': 'Transformation, Secrets, Life Span',
  'HouseTheme9': 'Luck, Wisdom, Foreign Travel',
  'HouseTheme10': 'Career, Reputation, Authority',
  'HouseTheme11': 'Gains, Friends, Desires',
  'HouseTheme12': 'Moksha, Isolation, Foreign Settlement',
  'MeaningTermAscendant': 'Ascendant (As)',
  'MeaningDescAscendant':
    'The sign rising on the eastern horizon at the time of birth; it shows your personality, appearance, and how you start things.',
  'MeaningTermExalted': 'Exalted',
  'MeaningDescExalted':
    'A planet is in its strongest and most positive position, giving good results.',
  'MeaningTermDebilitated': 'Debilitated',
  'MeaningDescDebilitated':
    'A planet is in its weakest position, causing challenges or reduced effectiveness.',
  'MeaningTermVargottam': 'Vargottam',
  'MeaningDescVargottam':
    'A planet is in the same sign in both the main chart and divisional chart, making its influence stronger.',
  'MeaningTermRetrograde': 'Retrograde',
  'MeaningDescRetrograde':
    'A planet appears to move backward, often giving mixed or unusual results.',
  'MeaningTermCombust': 'Combust',
  'MeaningDescCombust':
    'A planet is too close to the Sun, weakening its power and causing problems in its effects.',
  'PlanetNameSun': 'Sun',
  'PlanetKeywordsSun': 'Power, Authority, Ego',
  'PlanetNameMoon': 'Moon',
  'PlanetKeywordsMoon': 'Mind, Emotions, Nurture',
  'PlanetNameMars': 'Mars',
  'PlanetKeywordsMars': 'Energy, Courage, Aggression',
  'PlanetNameMercury': 'Mercury',
  'PlanetKeywordsMercury': 'Intelligence, Communication, Logic',
  'PlanetNameJupiter': 'Jupiter',
  'PlanetKeywordsJupiter': 'Wisdom, Expansion, Spirituality',
  'PlanetNameVenus': 'Venus',
  'PlanetKeywordsVenus': 'Love, Beauty, Luxury',
  'PlanetNameSaturn': 'Saturn',
  'PlanetKeywordsSaturn': 'Discpline, Hardship, Delay',
  'PlanetNameRahu': 'Rahu',
  'PlanetKeywordsRahu': 'Desire, Obsession, Illusion',
  'PlanetNameKetu': 'Ketu',
  'PlanetKeywordsKetu': 'Detachment, Past Life, Spirituality',
  'PositionTraits1': 'Courage, Action, Impulsive',
  'PositionTraits2': 'Stability, Patience, Stubborn',
  'PositionTraits3': 'Communication, Curious, Inconsistent',
  'PositionTraits4': 'Nurturing, Emotional, Moody',
  'PositionTraits5': 'Leadership, Creative, Egoistic',
  'PositionTraits6': 'Analytical, Practical, Overcritical',
  'PositionTraits7': 'Balanced, Charming, Indecisive',
  'PositionTraits8': 'Intense, Passionate, Secretive',
  'PositionTraits9': 'Adventurous, Optimistic, Restless',
  'PositionTraits10': 'Disciplined, Ambitious, Rigid',
  'PositionTraits11': 'Innovative, Humanitarian, Detached',
  'PositionTraits12': 'Compassionate, Spiritual, Escapist',
  'SrNo': 'S.No.',
  'Short': 'Short',
  'Keywords': 'Keywords',
  'Traits': 'Traits',
  'Zodiac': 'Zodiac Signs',
  'Term': 'Term',
  'Symbol': 'Symbol',
  'Meaning': 'Meaning',

  //AskExpert
  'BookConsultation': 'Book Consultation',
  'UpcomingAppointments': 'Upcoming Appointments',
  'Exp': 'Exp',
  'View': 'View',
  'Profile': 'Profile',
  'Language': 'Language',
  'Experience': 'Experience',
  'AboutAstrologer': 'About Astrologer',
  'Gallery': 'Gallery',
  'Fee': 'Fee',
  'BookNow': 'Book Now',
  'Date': 'Date',
  'Slots': 'Slots',
  'Slotsavailable': 'Slots available',
  'NoSlotsAvailable': 'No Slots Available',
  'Close': 'Close',
  'Schedule': 'Schedule',
  'Testimonials': 'Testimonials',
  'BookingDetails': 'Booking Details',
  'Time': 'Time',
  'Okay': 'Okay',
  'SelectDateTime': 'Select Date & Time',
  'AppointmentDetails': 'Appointment Details',
  'PriceDetails': 'Price Details',
  'Consultingfee': 'Consulting fee',
  'Total': 'Total',
  'Pay': 'Pay',

  //SubscriptionPlan screen
  'Feature1': 'Basic Astrological Details',
  'Feature2': 'Planetary Positions',
  'Feature3': 'Horoscope Charts',
  'Feature4': 'Planets Friendship Table',
  'Feature5': 'Dasha Analysis',
  'Feature6': 'Ascendant Report',
  'Feature7': 'Characteristics,  Lucky Gems, Day Of Fast',
  'Feature8': '12 Months Prediction',
  'Feature9': '60+ Page Kundli',
  'GetKundliReport': 'Get Kundli Report',
  'ViewSample': 'View Sample',
  'GetNow': 'Get Now',
  'Free': 'Free',
  'Premium': 'Premium',
  'Getyour': 'Get your',
  'detailedastrological': 'detailed astrological',
  'reportandmakeinformeddecisions': 'report and make informed decisions',

  //SampleKundliscreen
  'ViewFullscreen': 'View Full screen',
  'SampleKundli': 'Sample Kundli',
  'Download': 'Download',
  'Congratulations': 'Congratulations',
  'PaymentFailed': 'Payment Failed!',
  'PaymentSuccess': 'Your payment was successful.',
  'AppointmentSuccess': 'You have successfully booked an appointment',
  'KundliNote':
    'You’ve unlocked your Premium Kundli. Please download to view full report',
  'BackToHome': 'Back to Home',

  //DeleteModal
  'DeleteProfile': 'Delete Profile',
  'DeleteMessage':
    'Are you sure you want to delete this profile? This action cannot be undone.',
  'downloadTitle': 'Kundli Downloaded',
  'downloadDesc': 'Your kundli Downloaded Successfully.',
  'okay': 'Okay',
  'downlodingkundli': 'Downloading Kundli...',

  //AI Astrology homescreen modal
  'First2': 'First 5',
  'QuestionFree': 'Question Free',
  'description':
    'Ask anything and receive AI-powered astrology guidance tailored to your kundli.',
  'StartFree': 'Start Free',
  'LeavingSoon': 'Leaving Soon?',
  'LeavingSoondesc':
    'Your current conversation will end, but you can come back anytime.',
  'LeavingSoondesc2':
    'Your AI Vedic Astrology Consultation is Just One Click Away, To Change your Life.',

  //AI Astrology subscription screen
  'Pricing': 'Pricing',
  'BuyNow': 'Buy Now',
  'Payment': 'Payment',
  'PlanCost': 'Plan Cost',
  'GST': 'GST',
  'PayNow': 'Pay Now',

  //GetStartedScreen
  'DescriptionAi1':
    ' Blending ancient astrology with modern AI for personalized guidance.',
  'GetStarted': 'Get Started',

  //SelectProfileModal
  'SelectedProfile': 'Selected Profile',
  'AnalyseKundli': 'Analyse Kundli',

  //Chatscreen:
  'NewChat': 'New Chat',
  'Questionleft': 'Question left',
  'Upgrade': 'Upgrade',
  'Profiles': 'Profiles',
  'Leave': 'Leave',
  'WriteSomething': 'Write Something',
  'Tryagain': 'Try again',
  'StartAsking': 'Start Asking',
  'RedirectToHomeIn': 'We will redirect you to Chat in',
  'PaymentFailedDes':
    'Your transaction was not completed. Kindly try again or use a different payment method.',
  'PLAN_CREDITS': 'We’ve added {credits} questions to your current plan.',
  'Writefeedback': 'Write feedback',
  'Report': 'Report',
  'ShareFeedback': 'Share Feedback',
  'selectFeedbackError': 'Please select a feedback option',

  'feedback_option_1': 'Incorrect or incomplete',
  'feedback_option_2': 'Not what I asked for',
  'feedback_option_3': 'Slow or buggy',
  'feedback_option_4': 'Style or tone',
  'feedback_option_5': 'Safety or legal concern',
  'feedback_option_6': 'Other',

  'student': 'Student',
  'job': 'Job',
  'unemployed': 'Unemployed',
  'businessman': 'Businessman',
  'government_exam_preparation': 'Government Exam Preparation',

  'single': 'Single',
  'married': 'Married',
  'divorced': 'Divorced',
  'widowed': 'Widowed',
};