const Map<String, String> hi = {
  //splashScreen
  'SplashscreenText': 'व्यक्तिगत ज्योतिष के माध्यम से खुद को जानें',
  'Welcome': 'स्वागत है',
  'WelcomeSubText':
      'रोज़ाना सुझाव, उपयोगी जानकारियाँ और ब्रह्मांडीय मार्गदर्शन प्राप्त करें जो आपके दिन को दिशा देंगे।',
  'PersonalizedKundli': 'व्यक्तिगत कुंडली',
  'PersonalizedKundliSubText':
      'आपकी जन्म तिथि, समय और स्थान के आधार पर सटीक कुंडली',
  'MatchmakingSubText':
      'ज्योतिष के माध्यम से अपने साथी के साथ अपनी अनुकूलता जांचें।',
  'Next': 'आगे',
  'Getstarted': 'शुरू करें',

  //Login
  'enterCode': 'अपना सत्यापन कोड दर्ज करें',
  'invalidOtp': 'अमान्य ओटीपी नंबर',
  'enterOtp': 'कृपया 4 अंकों का ओटीपी नंबर दर्ज करें',
  'wrongOtp': 'अमान्य ओटीपी नंबर',
  'sentTo': 'भेजा गया',
  'didntReceive': 'ओटीपी नहीं मिला?',
  'resend': 'पुनः भेजें',
  'verify': 'सत्यापित करें',
  'privacyTitle': 'गोपनीयता नीति',
  'tncTitle': 'नियम और शर्तें',
  'tnc_Title': 'नियम व शर्तें',

  //Homescreen
  'AskAstrologer': 'ज्योतिषी से पूछें',
  'ViewAll': 'सभी देखें',
  'ViewDetails': 'विवरण देखें',
  'ReadMore': 'अधिक देखें',
  'ReadLess': 'कम देखें',
  'ReliableApp': 'विश्वसनीय ऐप',
  'SecurePayment': 'सुरक्षित भुगतान',
  'TrustedAstrologer': 'विश्वसनीय ज्योतिषी',
  'Horoscope': 'राशिफल',
  'Kundli': 'कुंडली',
  'Notification': 'अधिसूचना',
  'Partner': 'साथी',
  'Panchang': 'पंचांग',
  'ZodiacSign': 'राशि चिन्ह',
  'LuckyNumber': 'शुभ अंक',
  'LuckyColor': 'शुभ रंग',
  'TodayInsights': 'आज की जानकारियाँ',
  'Top10blogs': 'टॉप 10 ब्लॉग',
  'Weekyhoroscope': 'साप्ताहिक राशिफल',
  'VenusNaskshtra': ' शुक्र नक्षत्र',
  'NumerologyWeekly': 'साप्ताहिक अंकज्योतिष',
  'TodayMuhrat': 'आज की मुहूरत',
  'SunriseSunset': 'सूर्योदय - सूर्यास्त',
  'SunriseSunset1': 'सूर्योदय/सूर्यास्त',
  'MoonriseMoonset': 'चंद्रउदय - चंद्रअस्त',
  'MoonriseMoonset1': 'चंद्रउदय/चंद्रअस्त',
  'Auspicious': 'संयोजित',
  'Inauspicious': 'असंयोजित',
  'AbhijitMuhurat': 'अभिजीत मुहूर्त',
  'Rahukaal': 'राहु काल',
  'GulikaiKaal': 'गुलिक काल',
  'AbhijitMuhuratDescription':
      'यह दोपहर के आसपास का 48 मिनट का शुभ समय होता है, जो तब नए और महत्वपूर्ण कार्य शुरू करने के लिए सर्वोत्तम माना जाता है जब कोई अन्य शुभ मुहूर्त उपलब्ध न हो।',
  'RahukaalDescription':
      'यह प्रतिदिन लगभग 1.5 घंटे का अशुभ समय होता है। इस दौरान नए कार्य या महत्वपूर्ण काम शुरू करने से बचना चाहिए।',
  'GulikaiKaalDescription':
      'गुलिकाल प्रतिदिन का एक ऐसा समय होता है जो विलंब और बाधाओं से जुड़ा माना जाता है। इसे नए कार्य शुरू करने के लिए अशुभ माना जाता है।',
  'TodayHoroscope': 'आज का राशिफल',
  //ServiceScreen
  'WhatYouNeed': 'क्या आपको आपकी ज़रूरत की चीज़ नहीं मिली?',
  'ConnectAstrologer': 'हमारे ज्योतिषी से संपर्क करें।',
  'Ask': 'पूछें',
  'Service': 'सेवा',

  //YogaScreen
  'Heading':
      'योग आपके जन्म कुंडली में ग्रहों का विशेष संयोजन है जो आपके व्यक्तित्व, जीवन की घटनाओं और संबंधों को प्रभावित करता है।',
  'homeTab': 'होम',
  'serviceTab': 'सेवा',
  'aiAstro': 'आई आस्ट्रो',
  'expertTab': 'विशेषज्ञ',
  'profileTab': 'प्रोफ़ाइल',

  //Profile
  'title': 'प्रोफ़ाइल',
  'name': 'आपका नाम क्या है?',
  'Name': 'नाम',
  'gender': 'आपका लिंग क्या है?',
  'Gender': 'लिंग',
  'birthTime': 'जन्म का समय',
  'birthPlace': 'जन्म स्थान',
  'dob': 'जन्म तिथि',
  'logout': 'लॉग आउट',
  'logoutDesc': 'क्या आप वाकई लॉग आउट करना चाहते हैं',
  'delete': 'हटाएँ',
  'deleteAccountText': 'खाता हटाएँ',
  'deleteAccountDesc':
      'एक बार हटाए जाने के बाद, इस खाते तक दोबारा पहुँचा नहीं जा सकेगा।',
  'deleteAccountDesc1': 'क्या आप वाकई अपना खाता हटाना चाहते हैं?',
  'cancle': 'रद्द करें',
  'log_out': 'लॉग आउट करें',
  'deleteAccount': 'खाता हटा दो',
  'kundliTitle': 'मेरी कुंडली',
  'FreeKundli': 'फ्री कुंडली',
  'PremiumKundli': 'प्रीमियम कुंडली',
  'Purchasedon': 'खरीदा गया है',
  'noKundli': 'कोई कुंडली नहीं मिली',
  'noKundilDesc': 'कुंडली अनलॉक करें और अपना ब्रह्मांडीय मार्ग देखें।',
  'getKundli': 'अभी कुंडली प्राप्त करें',
  'profileDetailsTitle': 'प्रोफ़ाइल विवरण',
  'username': 'नाम',
  'userGender': 'लिंग',
  'accountSetting': 'खाता सेटिंग्स',
  'myDetails': 'मेरे विवरण',
  'SavedProfile': 'सहेजे गए प्रोफ़ाइल',
  'changeL': 'भाषा बदलें',
  'legal': 'कानूनी व गोपनीयता',
  'accountAction': 'खाता क्रियाएँ',
  'NoDetailsFound': 'कोई विवरण नहीं मिला',
  'Pleasefilldetailsforgetpersonalizedkundli':
      'कुंडली के लिए व्यक्तिगत विवरण भरें',
  'Letsgetstarted': 'शुरू करें',
  'SelectProfile': 'प्रोफ़ाइल चुनें',

  //PersonalInformationscreen
  'PersonalInformation': 'व्यक्तिगत जानकारी',
  'ProfileDetails': 'मेरे विवरण',
  'ProfileDetail': 'मेरे विवरण',
  'CompleteYourProfile': 'अपनी प्रोफ़ाइल पूरी करें',
  'MatchMaking': 'मैच मेकिंग',
  'KundaliAdd': 'मेरे प्रोफ़ाइल',
  'LetsGetStarted': 'चलिए शुरू करते हैं',
  'DataRequirementText':
      'सभी चार्ट और जानकारियाँ दिखाने के लिए हमें आपके डेटा की आवश्यकता है',
  'WhatIsYourName': 'आपका नाम क्या है?',
  'EnterYourName': 'अपना नाम दर्ज करें',
  'WhatIsYourGender': 'आपका लिंग क्या है?',
  'DateOfBirth': 'जन्म तिथि',
  'TimeOfBirth': 'जन्म समय',
  'PlaceOfBirth': 'जन्म स्थान',
  'Selectoftimingofbirth': 'जन्म समय का चयन करें',
  'Relationship': 'रिश्ता (वैकल्पिक)',
  'Occupation': 'पेशा (वैकल्पिक)',
  'SelectOccupation': 'पेशा चुनें',
  'EnterLocation': 'स्थान दर्ज करें',
  'SelectTime': 'समय चुनें',
  'SelectDate': 'तारीख चुनें',
  'SaveProfile': 'प्रोफ़ाइल सहेजें',
  'Save': 'सहेजें',
  'Proceed': 'आगे बढ़ें',
  'Submit': 'जमा करें',
  'Location': 'स्थान',
  'Male': 'पुरुष',
  'Female': 'महिला',

  //Validation Errors
  'NameError': 'कृपया अपना नाम दर्ज करें',
  'GenderError': 'कृपया अपना लिंग चुनें',
  'DobError': 'कृपया अपनी जन्म तिथि चुनें',
  'TobError': 'कृपया अपना जन्म का समय चुनें',
  'PobError': 'कृपया अपना जन्म स्थान चुनें',
  'connectionError': 'नेटवर्क त्रुटि। कृपया अपना इंटरनेट कनेक्शन जांचें।',

  //panchang
  'Muhurat': 'मुहूर्त',
  'TithiDescription':
      'यह चंद्रमा की अवस्था और दिन के स्वभाव को दर्शाता है—क्या यह शुरुआत, उत्सव या आत्मचिंतन के लिए उपयुक्त है।',
  'VaarDescription':
      'वार सप्ताह का दिन होता है, जिसका स्वामी एक ग्रह होता है, और प्रत्येक दिन अपनी खास ऊर्जा लिए होता है।',
  'NakshatraDescription':
      'नक्षत्र वह तारा होता है जिसमें चंद्रमा गतिशील होता है, और यह दिन की ऊर्जा तथा आपके कार्यों को प्रभावित करता है।',
  'KaranaDescription':
      'करण दिन को भागों में विभाजित करता है और केंद्रित कार्यों के लिए सही समय दर्शाता है।',
  'YogaDescription':
      'यह सूर्य–चंद्र के संयोग का फल होता है, जो बताता है कि दिन संतुलित, शक्तिशाली या चुनौतीपूर्ण है।',
  'Sunday': 'रविवार',
  'SundaySpecial': 'नेतृत्व और नए आरंभ के लिए शुभ',
  'SundayLord': 'सूर्य',
  'Monday': 'सोमवार',
  'MondaySpecial': 'शांति, भावनाओं और हीलिंग के लिए अच्छा',
  'MondayLord': 'चंद्र',
  'Tuesday': 'मंगलवार',
  'TuesdaySpecial': 'शक्ति, साहस और कार्यों के लिए अच्छा',
  'TuesdayLord': 'मंगल',
  'Wednesday': 'बुधवार',
  'WednesdaySpecial': 'संचार, सीखने और व्यापार के लिए शुभ',
  'WednesdayLord': 'बुध',
  'Thursday': 'गुरुवार',
  'ThursdaySpecial': 'ज्ञान, शिक्षण और विकास के लिए अच्छा',
  'ThursdayLord': 'गुरु',
  'Friday': 'शुक्रवार',
  'FridaySpecial': 'प्रेम, सौंदर्य और आराम के लिए अच्छा',
  'FridayLord': 'शुक्र',
  'Saturday': 'शनिवार',
  'SaturdaySpecial': 'अनुशासन, मेहनत और सहनशीलता के लिए अच्छा',
  'SaturdayLord': 'शनि',
  'TITHI': 'तिथि',
  'VAAR': 'वार',
  'NAKSHATRA': 'नक्षत्र',
  'KARANA': 'करण',
  'YOGA': 'योग',
  'Tithi': 'तिथि',
  'Start': 'प्रारंभ',
  'Diety': 'देवता',
  'NextTithi': 'अगली तिथि',
  'Lord': 'स्वामी',
  'NextVaar': 'अगला वार',
  'Nakshatra': 'नक्षत्र',
  'NextNakshatra': 'अगला नक्षत्र',
  'Karana': 'करण',

  //MatchMaking
  'AddPartner': 'साथी जोड़ें',
  'CheckCompatibility': 'अनुकूलता जाँचें',
  'SelectPartner': 'साथी चुनें',
  'AddProfile': 'प्रोफ़ाइल जोड़ें',
  'EditProfile': 'प्रोफ़ाइल संपादित करें',
  'ExcellentCompatibility': 'उत्कृष्ट अनुकूलता',
  'CompatibilityParameters': 'अनुकूलता पैरामीटर',
  'VeryPoorMatch': 'बहुत खराब मेल',
  'VeryPoorMatchTraits': 'बड़े अंतर, बार-बार मतभेद',
  'VeryPoorMatchDescription':
      'मूल्यों और संचार में बड़े अंतर। बहुत प्रयास के बिना संबंध चलना मुश्किल हो सकता है।',
  'PoorMatch': 'खराब मेल',
  'PoorMatchTraits': 'स्पष्ट चुनौतियाँ, तनाव',
  'PoorMatchDescription':
      'चुनौतियाँ और गलतफहमियाँ होने की संभावना। आगे बढ़ने के लिए धैर्य और समझदारी की आवश्यकता होती है।',
  'AverageMatch': 'औसत मेल',
  'AverageMatchTraits': 'कुछ समानताएँ, प्रयास की आवश्यकता',
  'AverageMatchDescription':
      'कुछ साझा रुचियाँ हैं, लेकिन मतभेदों को सँभालने के लिए समझौता और प्रयास जरूरी है।',
  'GoodMatch': 'अच्छा मेल',
  'GoodMatchTraits': 'संतुलित, संभालने योग्य अंतर',
  'GoodMatchDescription':
      'एक संतुलित संबंध जिसमें अंतर को संभाला जा सकता है। आपसी सहयोग से संबंध मजबूत बनता है।',
  'VeryGoodMatch': 'बहुत अच्छा मेल',
  'VeryGoodMatchTraits': 'मजबूत तालमेल, आपसी सहयोग',
  'VeryGoodMatchDescription':
      'मूल्यों और लक्ष्यों में मजबूत अनुकूलता। समझ और सहयोग संबंध को आगे बढ़ाते हैं।',
  'ExcellentMatch': 'उत्कृष्ट मेल',
  'ExcellentMatchTraits': 'गहरी अनुकूलता, दीर्घकालिक दृष्टि',
  'ExcellentMatchDescription':
      'उच्च अनुकूलता और साझा दृष्टिकोण। विश्वास और सामंजस्य इसे लंबे समय के लिए आदर्श बनाते हैं।',
  'Varna': 'वर्ण',
  'VarnaMatching': 'सामाजिक और मानसिक मेल, समान मूल्य',
  'Vasya': 'वश्य',
  'VasyaMatching': 'आकर्षण और प्रभाव',
  'Tara': 'तारा',
  'TaraMatching': 'तारकीय मेल, दंपत्ति के स्वास्थ्य और आयु की जांच',
  'Yoni': 'योनि',
  'YoniMatching': 'यौन मेल, संतुलित आकर्षण और ऊर्जा',
  'GrahaMaitri': 'ग्रह मैत्री',
  'GrahaMaitriMatching': 'मानसिक मित्रता और अनुकूलता',
  'Gana': 'गण',
  'GanaMatching': 'स्वभाव का मेल, संबंध में सामंजस्य',
  'Bhakoot': 'भकूट',
  'BhakootMatching': 'भावनात्मक जुड़ाव, समृद्धि और परिवार में सामंजस्य',
  'Nadi': 'नाड़ी',
  'NadiMatching': 'स्वास्थ्य, अनुवांशिकता और संतान संबंधी संभावनाएँ',
  'NoListFound': 'कोई सूची नहीं मिला',

  //Dosha
  'Dosh': 'दोष',
  'DoshDescription':
      'दोष जन्म कुंडली में ग्रहों की ऐसी असंतुलित स्थिति होती है, जिसके कारण जीवन में बाधाएँ और विलंब आते हैं।',
  'MangalDosha': 'मंगल दोष',
  'KaalsarpDosha': 'कालसर्प दोष',
  'PitraDosha': 'पितृ दोष',
  'MangalDoshaDescription':
      'मंगल दोष तब होता है जब कुंडली में मंगल की स्थिति विवाह में विलंब या समस्याएँ उत्पन्न करती है।',
  'KaalsarpDoshaDescription':
      'कालसर्प दोष तब होता है जब सभी ग्रह राहु और केतु के बीच स्थित होते हैं, जिससे जीवन में चुनौतियाँ आती हैं।',
  'PitraDoshaDescription':
      'पितृ दोष तब माना जाता है जब कुंडली में पूर्वजों के कर्मों का प्रभाव बाधाएँ उत्पन्न करता है।',
  'Yes': 'हाँ',
  'No': 'नहीं',
  'MANGLIK': 'मांगलिक',
  'ConsultHeading': 'हमारे ज्योतिष विशेषज्ञों से परामर्श करें',
  'ViewMore': 'और देखें',

  //Dasha
  'Dasha': 'दशा',
  'MahaDasha': 'महादशा',
  'AntaraDasha': 'अंतरदशा',
  'PratyantaraDasha': 'प्रत्यान्तर दशा',
  'MahaDashaDescription':
      'वैदिक ज्योतिष में मुख्य ग्रह अवधि। यह कई वर्षों तक चलती है और उस समय जीवन की घटनाओं की समग्र दिशा निर्धारित करती है।',
  'AntarDashaDescription':
      'महादशा के भीतर आने वाली उप-अवधि, जो किसी अन्य ग्रह द्वारा संचालित होती है। यह महादशा के प्रभावों को और अधिक स्पष्ट और विस्तृत करती है।',
  'PratyantaraDashaDescription':
      'अंतरदशा के भीतर आने वाली और छोटी उप-अवधि। यह जीवन की दैनिक घटनाओं और अल्पकालिक प्रभावों को दर्शाती है।',
  'End': 'अंत',
  'Dasha_Mars_Abbr': 'मं',
  'Dasha_Rahu_Abbr': 'राहु',
  'Dasha_Jupiter_Abbr': 'गुरु',
  'Dasha_Saturn_Abbr': 'शनि',
  'Dasha_Mercury_Abbr': 'बुध',
  'Dasha_Ketu_Abbr': 'केतु',
  'Dasha_Venus_Abbr': 'शुक्र',
  'Dasha_Sun_Abbr': 'सूर्य',
  'Dasha_Moon_Abbr': 'चंद्र',
  'Dasha_Ascendant_Abbr': 'लग्न',
  'Mars': 'मंगल',
  'Rahu': 'राहु',
  'Jupiter': 'गुरु',
  'Saturn': 'शनि',
  'Mercury': 'बुध',
  'Ketu': 'केतु',
  'Venus': 'शुक्र',
  'Sun': 'सूर्य',
  'Moon': 'चंद्र',
  'Ascendant': 'लग्न',

  //Yoga
  'Yoga': 'योग',
  'YogaDescription1':
      'योग आपकी जन्म कुंडली में ग्रहों का विशेष संयोजन होता है, जो आपकी व्यक्तित्व, जीवन की घटनाओं और संबंधों को प्रभावित करता है।',

  //SadeSatiscreen
  'SadeSati': 'साढ़े साती',
  'SadeSatiReport': 'साढ़े साती रिपोर्ट',
  'SadeSatiDescription':
      'यह उपयोगकर्ताओं को उनकी व्यक्तिगत साढ़े साती अवधि (पूर्व, वर्तमान और आने वाली) देखने में सहायता करता है।',
  'Phase': 'अवधि',

  //Hora Muhurat
  'HoraMuhurat': 'होरा मुहूर्त',
  'HoraMuhuratDescription':
      'यह उपयोगकर्ताओं को दैनिक ग्रह-आधारित घंटे (होरा) देखने और किसी भी तिथि के शुभ/अशुभ समय की जांच करने की सुविधा देता है।',

  //Horoscope
  'Today': 'आज',
  'ThisWeek': 'इस सप्ताह',
  'Health': 'स्वास्थ्य',
  'Love': 'प्रेम',
  'Wealth': 'धन',
  'Career': 'कार्य',
  'Family': 'परिवार',
  'Friends': 'मित्र',
  'Travel': 'यात्रा',
  'Status': 'स्थिति',
  'Finance': 'वित्त',
  'Aries': 'मेष',
  'Taurus': 'वृषभ',
  'Gemini': 'मिथुन',
  'Cancer': 'कर्क',
  'Leo': 'सिंह',
  'Virgo': 'कन्या',
  'Libra': 'तुला',
  'Scorpio': 'वृश्चिक',
  'Sagittarius': 'धनु',
  'Capricorn': 'मकर',
  'Aquarius': 'कुंभ',
  'Pisces': 'मीन',

  //Kundliscreen
  'NowGetFree': 'अब मुफ़्त',
  'Astrological': 'ज्योतिषीय',
  'ReportsText': 'रिपोर्ट प्राप्त करें और सही निर्णय लें',
  'LagnaChart': 'लग्न कुंडली',
  'NavamsaChart': 'नवांश कुंडली',
  'ChalitChart': 'चलित कुंडली',
  'Chalit': 'chalit',
  'LagnaChartDescription':
      'लग्न कुंडली (D1) आपकी व्यक्तित्व, जीवन पथ और आप दुनिया का सामना कैसे करते हैं, यह बताती है।',
  'NavamsaChartDescription':
      'नवांश कुंडली (D9) विवाह और साझेदारी में आपका विकास, मूल्य और ताकत दर्शाती है।',
  'ChalitChartDescription':
      'चलित कुंडली ग्रहों के प्रभाव को वास्तविक जीवन में दिखाती है, जहाँ ग्रहों की स्थितियों और वास्तविक अनुभवों के अनुसार भाव बदल जाते हैं।',
  'Retrograde': 'वक्री',
  'Combust': 'अस्त',
  'Exalted': 'उच्च',
  'Debilitated': 'नीच',
  'Vargottam': 'वर्गोत्तम',
  'StillConfuse': 'क्या आप अभी भी अपनी कुंडली के बारे में पढ़कर असमंजस में हैं?',
  'GetHelp': 'मदद प्राप्त करें',
  'KundliHouseGuide': 'कुंडली भाव मार्गदर्शिका',
  'HowToRead': 'चलित कुंडली कैसे पढ़ें?',
  'HowToReadNavamsa': 'नवांश कुंडली कैसे पढ़ें?',
  'SeeMore': 'और देखें',
  'SeeLess': 'कम देखें',
  'DownloadKundli': 'कुंडली डाउनलोड करें',
  'AriesLaganText':
      'आपकी लग्न राशि मेष है, जो आपको स्वाभाविक रूप से एक नेता बनाती है।',
  'TaurusLaganText':
      'आपकी लग्न राशि वृषभ है, जो आपको विश्वसनीय और स्थिर स्वभाव का बनाती है।',
  'GeminiLaganText':
      'आपकी लग्न राशि मिथुन है, जो आपको जिज्ञासु और अनुकूलनशील बनाती है।',
  'CancerLaganText':
      'आपकी लग्न राशि कर्क है, जो आपको भावुक, देखभाल करने वाला और संरक्षक बनाती है।',
  'LeoLaganText':
      'आपकी लग्न राशि सिंह है, जो आपको आत्मविश्वासी और रचनात्मक बनाती है।',
  'VirgoLaganText':
      'आप की लग्न राशि कन्या है, जो आपको व्यावहारिक और विवरण-उन्मुख बनाती है।',
  'LibraLaganText':
      'आपकी लग्न राशि तुला है, जो आपको संतुलित, कूटनीतिक और आकर्षक बनाती है।',
  'ScorpioLaganText':
      'आपकी लग्न राशि वृश्चिक है, जो आपको गहन और दृढ़निश्चयी बनाती है।',
  'SagittariusLaganText':
      'आपकी लग्न राशि धनु है, जो आपको साहसी, आशावादी और खोजी स्वभाव का बनाती है।',
  'CapricornLaganText':
      'आपकी लग्न राशि मकर है, जो आपको अनुशासित, जिम्मेदार और लक्ष्य-उन्मुख बनाती है।',
  'AquariusLaganText':
      'आपकी लग्न राशि कुंभ है, जो आपको नवाचारी, स्वतंत्र और प्रगतिशील सोच वाला बनाती है।',
  'PiscesLaganText':
      'आपकी लग्न राशि मीन है, जो आपको दयालु, कल्पनाशील और संवेदनशील बनाती है।',
  'AriesNavamText':
      'आपकी नवांश लग्न राशि मेष है, जो आपको आंतरिक साहस और रिश्तों व व्यक्तिगत विकास में अग्रणी सोच देती है।',
  'TaurusNavamText':
      'आपकी नवांश लग्न राशि वृषभ है, जो आपको स्थिर, धैर्यवान और गहरे भावनात्मक सुरक्षा पर केंद्रित बनाती है।',
  'GeminiNavamText':
      'आपकी नवांश लग्न राशि मिथुन है, जो आपको मानसिक रूप से सक्रिय और रिश्तों से सीखने के लिए खुला बनाती है।',
  'CancerNavamText':
      'आपकी नवांश लग्न राशि कर्क है, जो आपको भावनात्मक रूप से संवेदनशील और पोषण करने वाला स्वभाव देती है।',
  'LeoNavamText':
      'आपकी नवांश लग्न राशि सिंह है, जो आपको आत्मविश्वास, उदारता और रिश्तों में दिल से अभिव्यक्ति की इच्छा देती है।',
  'VirgoNavamText':
      'आपकी नवांश लग्न राशि कन्या है, जो आपको विश्लेषणात्मक, सेवा-उन्मुख और स्वयं व दूसरों में सुधार की भावना वाला बनाती है।',
  'LibraNavamText':
      'आपकी नवांश लग्न राशि तुला है, जो आपको संतुलन, न्याय और रिश्तों में सामंजस्य की गहरी समझ देती है।',
  'ScorpioNavamText':
      'आपकी नवांश लग्न राशि वृश्चिक है, जो आपको भावनात्मक गहराई, दृढ़ता और रिश्तों में परिवर्तनकारी दृष्टिकोण देती है।',
  'SagittariusNavamText':
      'आपकी नवांश लग्न राशि धनु है, जो आपको आशावादी, साहसी और आध्यात्मिक रूप से प्रेरित बनाती है।',
  'CapricornNavamText':
      'आपकी नवांश लग्न राशि मकर है, जो आपको अनुशासन, धैर्य और रिश्तों में जिम्मेदार दृष्टिकोण देती है।',
  'AquariusNavamText':
      'आपकी नवांश लग्न राशि कुंभ है, जो आपको आदर्शवादी, खुले विचारों वाला और अनोखे संबंधों की ओर आकर्षित बनाती है।',
  'PiscesNavamText':
      'आपकी नवांश लग्न राशि मीन है, जो आपको दयालु, संवेदनशील और आध्यात्मिक जुड़ाव की गहरी इच्छा वाला बनाती है।',
  'Personality1': 'व्यक्तित्व',
  'Wealth1': 'धन',
  'Communication1': 'संचार',
  'Home1': 'घर',
  'Creativity1': 'रचनात्मकता',
  'Health1': 'स्वास्थ्य',
  'Marriage1': 'विवाह',
  'Transformation1': 'परिवर्तन',
  'Luck1': 'भाग्य',
  'Career1': 'करियर',
  'Friends1': 'मित्र',
  'Spirituality1': 'आध्यात्मिकता',
  'House': 'घर',
  'InnerSelf': 'आंतरिक स्व',
  'FamilyValues': 'परिवारिक मूल्य',
  'MarriageEfforts': 'विवाह प्रयास',
  'DomesticPeace': 'घरेलू शांति',
  'LoveInMarriage': 'विवाह में प्रेम',
  'Challenges': 'चुनौतियाँ',
  'SpouseNature': 'जीवनसाथी का स्वभाव',
  'Intimacy': 'निजता / अंतरंगता',
  'SpiritualGrowth': 'आध्यात्मिक विकास',
  'MarriageDuty': 'विवाहिक कर्तव्य',
  'SpouseSupport': 'जीवनसाथी का सहयोग',
  'Isolation': 'एकांत / अलगाव',
  // HouseScreen
  'RulingPlanet': 'स्वामी ग्रह',
  'HouseAnalysis': 'भाव विश्लेषण',
  'PlanetsOnThisHouse': 'इस भाव में स्थित ग्रह',
  'Degree': 'डिग्री',
  'Longitude': 'देशांतर',
  'Pada': 'पाद',
  'Rashi': 'राशि',
  'Previous': 'पिछला',
  //KundliChartRead

  'PositionOfHouses': 'भावों की स्थिति और उनके गुण',
  'Position': 'स्थिति',
  'Planet': 'ग्रह',
  'Glossary': 'शब्दावली',
  'HowToReadKundliChart': 'कुंडली चार्ट कैसे पढ़ें?',
  'Themes': 'गुण',
  'HouseTheme1': 'व्यक्तित्व, स्वास्थ्य, पहचान',
  'HouseTheme2': 'धन, वाणी, मूल्य',
  'HouseTheme3': 'भाई-बहन, साहस, प्रयास',
  'HouseTheme4': 'घर, माता, भावनाएँ',
  'HouseTheme5': 'रचनात्मकता, संतान, पूर्व जन्म',
  'HouseTheme6': 'सेवा, शत्रु, चुनौतियाँ',
  'HouseTheme7': 'साथी, विवाह, अनुबंध',
  'HouseTheme8': 'परिवर्तन, रहस्य, आयु',
  'HouseTheme9': 'भाग्य, ज्ञान, विदेश यात्रा',
  'HouseTheme10': 'करियर, प्रतिष्ठा, अधिकार',
  'HouseTheme11': 'लाभ, मित्र, इच्छाएँ',
  'HouseTheme12': 'मोक्ष, एकांत, विदेशी निवास',
  'MeaningTermAscendant': 'लग्न (As)',
  'MeaningDescAscendant':
      'जन्म के समय पूर्व दिशा में उगने वाली राशि; यह आपका व्यक्तित्व, रूप-रंग और किसी भी कार्य की शुरुआत को दर्शाती है।',
  'MeaningTermExalted': 'उच्च',
  'MeaningDescExalted':
      'जब ग्रह अपनी सबसे मजबूत स्थिति में होता है, तब बहुत अच्छे परिणाम देता है।',
  'MeaningTermDebilitated': 'नीच',
  'MeaningDescDebilitated':
      'जब ग्रह अपनी सबसे कमजोर स्थिति में होता है, तब चुनौतियाँ या कमजोर परिणाम देता है।',
  'MeaningTermVargottam': 'वर्गोत्तम',
  'MeaningDescVargottam':
      'जब ग्रह मुख्य कुंडली और विभाजित कुंडली दोनों में एक ही राशि में हो, तो उसका प्रभाव और अधिक शक्तिशाली होता है।',
  'MeaningTermRetrograde': 'वक्री',
  'MeaningDescRetrograde':
      'जब ग्रह उल्टी दिशा में चलता हुआ प्रतीत होता है, तब यह मिश्रित या असामान्य परिणाम देता है।',
  'MeaningTermCombust': 'अस्त',
  'MeaningDescCombust':
      'जब ग्रह सूर्य के बहुत करीब होता है, तो उसकी शक्ति कम हो जाती है और उसके फल कमजोर हो जाते हैं।',
  'PlanetNameSun': 'सूर्य',
  'PlanetKeywordsSun': 'शक्ति, अधिकार, अहंकार',
  'PlanetNameMoon': 'चंद्र',
  'PlanetKeywordsMoon': 'मन, भावनाएँ, पालन-पोषण',
  'PlanetNameMars': 'मंगल',
  'PlanetKeywordsMars': 'ऊर्जा, साहस, आक्रामकता',
  'PlanetNameMercury': 'बुध',
  'PlanetKeywordsMercury': 'बुद्धि, संचार, तर्क',
  'PlanetNameJupiter': 'गुरु',
  'PlanetKeywordsJupiter': 'ज्ञान, विस्तार, आध्यात्मिकता',
  'PlanetNameVenus': 'शुक्र',
  'PlanetKeywordsVenus': 'प्रेम, सुंदरता, विलासिता',
  'PlanetNameSaturn': 'शनि',
  'PlanetKeywordsSaturn': 'अनुशासन, कठिनाई, विलंब',
  'PlanetNameRahu': 'राहु',
  'PlanetKeywordsRahu': 'इच्छा, आसक्ति, भ्रम',
  'PlanetNameKetu': 'केतु',
  'PlanetKeywordsKetu': 'वैराग्य, पूर्व जन्म, आध्यात्मिकता',
  'PositionTraits1': 'साहस, क्रियाशील, आवेगी',
  'PositionTraits2': 'स्थिरता, धैर्य, जिद्दी',
  'PositionTraits3': 'संचार, जिज्ञासु, अस्थिर',
  'PositionTraits4': 'पालन-पोषण, भावुक, मूडी',
  'PositionTraits5': 'नेतृत्व, रचनात्मक, अहंकारी',
  'PositionTraits6': 'विश्लेषणात्मक, व्यावहारिक, अतिविचार करने वाला',
  'PositionTraits7': 'संतुलित, आकर्षक, निर्णयहीन',
  'PositionTraits8': 'तीव्र, जुनूनी, रहस्यमयी',
  'PositionTraits9': 'साहसी, आशावादी, बेचैन',
  'PositionTraits10': 'अनुशासित, महत्वाकांक्षी, कठोर',
  'PositionTraits11': 'नवोन्मेषी, मानवतावादी, अलग-थलग',
  'PositionTraits12': 'दयालु, आध्यात्मिक, escapist (भागने वाला)',
  'SrNo': 'संख्या',
  'Short': 'शोध',
  'Keywords': 'शब्द',
  'Traits': 'विशेषता',
  'Zodiac': 'जोड़ी',
  'Term': 'शब्द',
  'Symbol': 'चिह्न',
  'Meaning': 'सम्पादन',

  //AskExpert
  'BookConsultation': 'सलाह बुक करें',
  'UpcomingAppointments': 'आगामी अपॉइंटमेंट',
  'Exp': 'अनुभव',
  'View': 'देखें',
  'Profile': 'प्रोफ़ाइल',
  'Language': 'भाषा',
  'Experience': 'अनुभव',
  'AboutAstrologer': 'ज्योतिषी के बारे में',
  'Gallery': 'गैलरी',
  'Fee': 'शुल्क',
  'BookNow': 'अभी बुक करें',
  'Date': 'तारीख',
  'Slots': 'स्लॉट्स',
  'Slotsavailable': 'स्लॉट उपलब्ध',
  'NoSlotsAvailable': 'कोई स्लॉट उपलब्ध नहीं है',
  'Close': 'बंद करें',
  'Schedule': 'अनुसूची',
  'Testimonials': 'टेस्टिमोनियल्स',
  'BookingDetails': 'बुकिंग विवरण',
  'Time': 'समय',
  'Okay': 'ठीक है',
  'SelectDateTime': 'तारीख और समय का चयन करें',
  'AppointmentDetails': 'अपॉइंटमेंट विवरण',
  'PriceDetails': 'शुल्क विवरण',
  'Consultingfee': 'ज्योतिषी की शुल्क',
  'Total': 'कुल',
  'Pay': 'भुगतान करें',

  //SubscriptionPlan screen

  'Feature1': 'बुनियादी ज्योतिषीय विवरण',
  'Feature2': 'ग्रह स्थितियाँ',
  'Feature3': 'कुंडली चार्ट ',
  'Feature4': 'ग्रह मित्रता तालिका',
  'Feature5': 'दशा विश्लेषण',
  'Feature6': ' लग्न रिपोर्ट ',
  'Feature7': 'व्यक्तित्व गुण, शुभ रत्न, उपवास का दिवस',
  'Feature8': '12 महीनों का भविष्यफल ',
  'Feature9': '60+ पेज की विस्तृत कुंडली ',
  'GetKundliReport': 'कुंडली रिपोर्ट प्राप्त करें',
  'ViewSample': 'उदाहरण देखें',
  'GetNow': 'अभी प्राप्त करें',
  'Free': 'फ्री',
  'Premium': 'प्रीमियम',
  'Getyour': 'अपनी',
  'detailedastrological': 'विस्तृत ज्योतिषीय ',
  'reportandmakeinformeddecisions': 'विवरण प्राप्त करें और सही निर्णय लें',

  //SampleKundliscreen
  'ViewFullscreen': 'फूलस्क्रीन देखें',
  'SampleKundli': 'उदाहरण कुंडली',

  'Download': 'डाउनलोड करें',
  'Congratulations': 'बधाई हो',
  'PaymentFailed': 'आपका भुगतान विफल हो गया।',
  'PaymentSuccess': 'आपका भुगतान सफल रहा।',
  'AppointmentSuccess': 'आपने सफलतापूर्वक अपॉइंटमेंट बुक कर लिया है',
  'KundliNote':
      'आपने अपनी प्रीमियम कुंडली अनलॉक कर ली है। पूरी रिपोर्ट देखने के लिए डाउनलोड करें',
  'BackToHome': 'होम पर वापस जाएं',

  //DeleteModal
  'DeleteProfile': 'प्रोफ़ाइल हटाएँ',
  'DeleteMessage':
      'क्या आप वाकई इस प्रोफ़ाइल को हटाना चाहते हैं? यह क्रिया वापस नहीं की जा सकती।',
  'downloadTitle': 'कुंडली डाउनलोड हो गई',
  'downloadDesc': 'आपकी कुंडली सफलतापूर्वक डाउनलोड हो गई है।',
  'okay': 'ठीक है',
  'downlodingkundli': 'कुंडली डाउनलोड हो रही है...',

  //AI Astrology homescreen modal
  'First2': 'पहले 5',
  'QuestionFree': 'प्रश्न निःशुल्क',
  'description':
      'कुछ भी पूछें और अपनी कुंडली के अनुसार एआई-आधारित ज्योतिषीय मार्गदर्शन प्राप्त करें।',
  'StartFree': 'मुफ्त शुरू करें',
  'LeavingSoon': 'जल्द जा रहे हैं?',
  'LeavingSoondesc':
      'आपकी वर्तमान बातचीत समाप्त हो जाएगी, लेकिन आप कभी भी वापस आ सकते हैं।',
  'LeavingSoondesc2':
      'आपकी एआई वैदिक ज्योतिष परामर्श बस एक क्लिक दूर है, जो आपके जीवन को बदल सकता है।',

  //AI Astrology subscription screen
  'Pricing': 'मूल्य निर्धारण',
  'BuyNow': 'अभी खरीदें',
  'Payment': 'भुगतान',
  'PlanCost': 'प्लान की कीमत',
  'GST': 'जीएसटी',
  'PayNow': 'अभी भुगतान करें',

  // GetStartedScreen
  'DescriptionAi1':
      'व्यक्तिगत मार्गदर्शन के लिए प्राचीन ज्योतिष और आधुनिक AI का संगम।',
  'GetStarted': 'शुरू करें',

  // SelectProfileModal
  'SelectedProfile': 'चयनित प्रोफ़ाइल',
  'AnalyseKundli': 'कुंडली का विश्लेषण करें',

  // Chatscreen
  'NewChat': 'नई चैट',
  'Questionleft': 'बचे हुए प्रश्न',
  'Upgrade': 'अपग्रेड',
  'Profiles': 'प्रोफाइल्स',
  'Leave': 'छोड़ें',
  'WriteSomething': 'कुछ लिखें',
  'Tryagain': 'फिर से प्रयास करें',
  'StartAsking': 'प्रश्न शुरू करें',
  'RedirectToHomeIn': 'हम आपको चैट में रीडायरेक्ट करेंगे',
  'PaymentFailedDes':
      'आपका लेन-देन पूरा नहीं हो सका। कृपया पुनः प्रयास करें या किसी अन्य भुगतान विधि का उपयोग करें।',
  'PLAN_CREDITS': 'हमने आपके वर्तमान प्लान में {credits} प्रश्न जोड़ दिए हैं।',
  'Writefeedback': 'प्रतिक्रिया लिखें',
  'Report': 'रिपोर्ट',
  'ShareFeedback': 'फीडबैक साझा करें',
  'selectFeedbackError': 'कृपया एक फीडबैक विकल्प चुनें',

  'feedback_option_1': 'गलत या अधूरा',
  'feedback_option_2': 'जो मैंने पूछा था वह नहीं',
  'feedback_option_3': 'धीमा या त्रुटिपूर्ण',
  'feedback_option_4': 'स्टाइल या टोन',
  'feedback_option_5': 'सुरक्षा या कानूनी चिंता',
  'feedback_option_6': 'अन्य',

  'student': 'छात्र',
  'job': 'नौकरी',
  'unemployed': 'बेरोजगार',
  'businessman': 'व्यवसायी',
  'government_exam_preparation': 'सरकारी परीक्षा की तैयारी',

  'single': 'अविवाहित',
  'married': 'विवाहित',
  'divorced': 'तलाकशुदा',
  'widowed': 'विधवा / विधुर',
};