name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  pinput: ^5.0.0
  sms_autofill: ^2.3.0
  cupertino_icons: ^1.0.8
  go_router: ^17.2.1
  flutter_native_splash: ^2.4.7
  flutter_riverpod: ^2.5.1
  http: ^1.6.0
  dio: ^5.4.0
  talker: ^4.0.0
  talker_dio_logger: ^4.0.0
  talker_riverpod_logger: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/common_image/
    - assets/images/splash_screen/
    - assets/images/view_pager_screen_image/
    - assets/images/login_screen_image/
    - assets/images/bottom_tab_image/
    - assets/images/homes_screen_image/
    - assets/images/profile_screen_image/
    - assets/images/service_screen_image/
    - assets/images/yoga_screen_image/
    - assets/images/matchmaking_screen_image/
    - assets/images/dasha_screen_image/
    - assets/images/dosh_screen_image/
    - assets/images/kundli_screen_image/
    - assets/images/horoscope_screen_image/
    - assets/images/panchang_screen_image/
    - assets/images/book_consultation_screen_image/
    - assets/images/subscriptionplan_screen_image/
    - assets/images/ai_screen_image/


# ✅ OUTSIDE flutter (IMPORTANT)
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/Logo.png

  android: true
  ios: true

  android_12:
    image: assets/images/Logo.png
    color: "#ffffff"